Testing: Increase test coverage (#16)
* Add work flow to run basic tests on MacOS
* Add device tests in githubactions workflow

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -71,7 +71,7 @@ jobs:
 
           mkdir build
           cd build
-          cmake -DWITHOUT_YKYH=1 -DBUILD_ONLY_LIB=ON -DENABLE_CERT_COMPRESS=OFF -DWITHOUT_MANPAGES=1 .. 
+          cmake -DWITHOUT_YKYH=1 -DBUILD_ONLY_LIB=OFF -DENABLE_CERT_COMPRESS=OFF -DWITHOUT_MANPAGES=1 .. 
           cmake --build .
  
 
@@ -98,6 +98,63 @@ jobs:
           export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/yubihsm-shell/build/lib
           
           cargo test
+
+      - name: prepare ghostunnel
+        env:
+          TLSPWD: ${{ secrets.TLSKEY }}
+          # GODEBUG required for ghostunnel to temporarily enable Common Name matching
+          GODEBUG: x509ignoreCN=0
+        run: |
+          curl -o /tmp/ghostunnel -L https://github.com/ghostunnel/ghostunnel/releases/download/v1.6.0/ghostunnel-v1.6.0-linux-amd64
+          chmod +x /tmp/ghostunnel
+          openssl aes-256-cbc \
+            -k "$TLSPWD" \
+            -md sha256 \
+            -in yubihsm-manager/.ci/client-combined.pem.enc \
+            -out yubihsm-manager/.ci/client-combined.pem \
+            -d
+          /tmp/ghostunnel client \
+            --listen localhost:12345 \
+            --target hsm-connector01.sthlm.in.yubico.org:8443 \
+            --keystore yubihsm-manager/.ci/client-combined.pem \
+            --cacert yubihsm-manager/.ci/server-crt.pem > /dev/null 2>&1 &
+          sleep 3
+          DEFAULT_CONNECTOR_URL=$(curl -s http://localhost:12345/dispatcher/request)
+          test -n "$DEFAULT_CONNECTOR_URL" || (echo "Unable to obtain a connector URL, aborting"; exit 1)
+          echo "DEFAULT_CONNECTOR_URL=$DEFAULT_CONNECTOR_URL" >> $GITHUB_ENV
+
+      - name: reset the hsm
+        working-directory: yubihsm-manager
+        run: |
+          #export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/yubihsm-shell/build/lib
+          #./target/debug/yubihsm-manager -c "$DEFAULT_CONNECTOR_URL" -p password reset
+          $GITHUB_WORKSPACE/yubihsm-shell/build/src/yubihsm-shell --connector "$DEFAULT_CONNECTOR_URL" -p password -a reset
+          sleep 3
+
+      - name: test yubihsm-manager commands
+        working-directory: yubihsm-manager
+        run: |
+          set -x -e
+          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/yubihsm-shell/build/lib
+          ./target/debug/yubihsm-manager -c "$DEFAULT_CONNECTOR_URL" get-device-info
+          ./target/debug/yubihsm-manager -c "$DEFAULT_CONNECTOR_URL" get-device-publickey
+
+      - name: run device tests
+        working-directory: yubihsm-manager
+        run: |
+          set -x -e
+          export PATH=$PATH:$HOME/.cargo/bin
+          export YUBIHSM_LIB_DIR=$GITHUB_WORKSPACE/yubihsm-shell/build/lib
+          export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/yubihsm-shell/build/lib
+          export YUBIHSM_CONNECTOR=$DEFAULT_CONNECTOR_URL
+          cargo test --features device-tests -- --test-threads=1
+
+      - name: cleanup
+        if: ${{ always() }}
+        run: |
+          if [ -n "$DEFAULT_CONNECTOR_URL" ]; then
+            curl -s http://localhost:12345/dispatcher/release?connector=$DEFAULT_CONNECTOR_URL
+          fi
 
   Windows:
     name: Windows
@@ -159,3 +216,52 @@ jobs:
           $env:PATH+=";$env:GITHUB_WORKSPACE/manager/bin;C:/vcpkg/packages/openssl_x64-windows/bin"
           cargo.exe test
 
+  macOS:
+    name: macOS
+    runs-on: macos-latest
+
+    steps:
+      - name: clone repository
+        uses: actions/checkout@v4
+        with:
+          path: yubihsm-manager
+
+      - name: install libyubihsm
+        env:
+          LIBYUBIHSM_VERSION: 2.7.2
+        run: |
+          set -e -o pipefail
+          set -x
+
+          brew update
+          brew reinstall openssl@3
+
+          cd ..
+          curl -L --max-redirs 2 -o yubihsm-shell-installer.pkg https://developers.yubico.com/yubihsm-shell/Releases/yubihsm-shell-$LIBYUBIHSM_VERSION-mac-universal.pkg
+          sudo installer -verbose -pkg yubihsm-shell-installer.pkg -target /
+
+      - name: Build yubihsm-manager
+        working-directory: yubihsm-manager
+        run: |
+          set -x -e
+
+          export PATH=$PATH:$HOME/.cargo/bin
+          if [[ ! -x $(command -v rustc) ]]; then
+            curl -o rustup.sh https://sh.rustup.rs
+            bash ./rustup.sh -y
+          fi
+
+          YUBIHSM_LIB_DIR=/usr/local/lib cargo build
+
+          export DYLD_LIBRARY_PATH=/usr/local/lib
+          ./target/debug/yubihsm-manager --version
+          ./target/debug/yubihsm-manager --help
+
+      - name: Run static tests
+        working-directory: yubihsm-manager
+        run: |
+          set -x -e
+          export PATH=$PATH:$HOME/.cargo/bin
+          export DYLD_LIBRARY_PATH=/usr/local/lib
+
+          cargo test
